<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NIK Ayah_Dimnik_ayah</name>
   <tag></tag>
   <elementGuidId>53140f8c-4188-414f-b11c-9adb75027a9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dim-nik_ayah</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dim-nik_ayah']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49afd7d3-0428-4b22-b209-bcd77a35b5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>67684de9-560a-453f-9e11-c3edd4c34d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dim-nik_ayah</value>
      <webElementGuid>c9056550-8699-4e6b-9342-6dabdae29f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>372cdd87-dc8f-400e-9738-783a799b918b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Dim[nik_ayah]</value>
      <webElementGuid>792b55f3-e910-41f7-a7a3-b5b8b544e383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>9549e19a-bf9f-4596-8463-1d2be9df8eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>NIK Ayah</value>
      <webElementGuid>d145c2dd-456a-4c4e-a091-84b713eb27af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dim-nik_ayah&quot;)</value>
      <webElementGuid>ceba923f-729e-4492-aca1-a38b61eb5933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>00876542845298</value>
      <webElementGuid>b431c84c-82cc-4cfd-a827-b97382b1fa99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dim-nik_ayah']</value>
      <webElementGuid>a1d14f2b-d119-413f-b806-4f51589ecc4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab_4']/div[5]/div/input</value>
      <webElementGuid>6e1841ab-76c4-4bce-b5df-825a4c18ccee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[5]/div/input</value>
      <webElementGuid>dec726c0-a85c-42cc-898a-1497ad374c6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dim-nik_ayah' and @name = 'Dim[nik_ayah]' and @placeholder = 'NIK Ayah']</value>
      <webElementGuid>fb5480be-0249-4d6e-b2dc-80478d3c4c34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
