<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama_Dimnama</name>
   <tag></tag>
   <elementGuidId>45112106-5743-40bf-a558-03adf33d9364</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dim-nama</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dim-nama']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53b6b16f-e52c-4fab-9ec0-15ac70b1a3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3fc86c66-1f1d-4845-930c-646a1e5e4a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dim-nama</value>
      <webElementGuid>8dd28246-a5af-4bd1-9055-af27c7761b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2540a372-5f77-46df-bc36-d3d86b33310f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Dim[nama]</value>
      <webElementGuid>08b79364-b9cf-4f3f-aec0-c740e08d6c85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Emy Sonia Sinambela</value>
      <webElementGuid>4705fb60-5b5d-4dec-b999-ca4f153c221a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Lengkap</value>
      <webElementGuid>b49ee281-bb21-4955-a068-cd3e2178854b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1e25c26f-5eaa-411d-99df-26f71d9600df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dim-nama&quot;)</value>
      <webElementGuid>a4f17046-2f62-4186-b68d-40df006b83da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dim-nama']</value>
      <webElementGuid>03c5be19-d967-4cb0-a8bb-d1e1c7ad7ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='grid-system1-body']/div[2]/div/input</value>
      <webElementGuid>ef8020f2-b86e-42b4-852c-e493b2f8475f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>a239a2dc-b872-4ed6-a966-fbd3cd25233a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dim-nama' and @name = 'Dim[nama]' and @placeholder = 'Nama Lengkap']</value>
      <webElementGuid>98d03841-04e3-439a-96b0-6ee8f1972cd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
