<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NIK Ibu_Dimnik_ibu</name>
   <tag></tag>
   <elementGuidId>5a4fc259-a518-43df-a224-a88c70f6ad1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dim-nik_ibu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dim-nik_ibu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75d7a8ad-a883-489a-8593-65283815c192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6ccd2b71-9aef-4743-81e1-0826f8d97443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dim-nik_ibu</value>
      <webElementGuid>92d3a78e-fd26-49c5-a622-48260e8eae4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fa1967b8-456c-471f-86e2-7d43dce42f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Dim[nik_ibu]</value>
      <webElementGuid>ff5fbd80-8bb4-458a-bdc1-bffb4a0e2037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>fe5611c2-b299-458b-b811-ad0eea129a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>NIK Ibu</value>
      <webElementGuid>ebd232ca-6fd1-479d-9a67-62dfb9347157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dim-nik_ibu&quot;)</value>
      <webElementGuid>966aaa0f-1b2f-4e6b-b40b-8b983244cf6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>00836514386465</value>
      <webElementGuid>bc792d52-86af-483c-a2c6-21c4ea4dfa44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dim-nik_ibu']</value>
      <webElementGuid>a0b1d8ea-46b0-42ea-b47e-c4dea4dbe1c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab_4']/div[6]/div/input</value>
      <webElementGuid>7628678e-e50f-42f2-9053-a896dcb065f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>d661580c-ac7d-4531-bd4e-d03b4e7c2e95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dim-nik_ibu' and @name = 'Dim[nik_ibu]' and @placeholder = 'NIK Ibu']</value>
      <webElementGuid>35182f57-6c9b-4350-9d50-53f1ea540318</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
