<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Ayah_Dimnama_ayah</name>
   <tag></tag>
   <elementGuidId>b1f1a6d3-42da-4953-ab0b-37510178a4e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dim-nama_ayah</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dim-nama_ayah']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4010242d-384c-444a-a8be-7abc876e6a8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1cc44d92-bd00-4b4f-a294-2714118ecf8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dim-nama_ayah</value>
      <webElementGuid>c26696fb-36b3-4d7f-ab9f-9e20374304bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2f0d11c4-4000-4f50-a3b0-f5ce8c61eb2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Dim[nama_ayah]</value>
      <webElementGuid>b7b5d5d4-c4eb-4d75-a511-0940023e187f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Rutman Sinambela</value>
      <webElementGuid>602f830b-58a4-4cc1-b869-93fd056aa78d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>6c4884e1-c0ef-4b0c-81fc-86c096ec8367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Ayah</value>
      <webElementGuid>3581d9e6-1d73-4f8c-9c2a-ea5feb16ba1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>13fbf4b0-8ce0-4516-a750-177554d93f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dim-nama_ayah&quot;)</value>
      <webElementGuid>c8795209-53fe-436e-a342-9a4c58cb10fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dim-nama_ayah']</value>
      <webElementGuid>df1005ef-fc70-4ddf-a05b-4a5865aff459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab_4']/div[3]/div/input</value>
      <webElementGuid>d338f53a-5406-498b-a609-ce8918a00517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/input</value>
      <webElementGuid>8bcd442d-e107-40ec-8c9a-fc657c428134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dim-nama_ayah' and @name = 'Dim[nama_ayah]' and @placeholder = 'Nama Ayah']</value>
      <webElementGuid>a880d78d-7b78-4acd-b738-53761321bc59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
