<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Asal Sekolah_asal_sekolah_id-fake</name>
   <tag></tag>
   <elementGuidId>d61df505-b7cc-4f7c-a883-f1e2b6146e66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#w1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='w1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4432446-afa4-4f0c-81fa-9f9667ad3c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>153a0c57-10fb-4fef-8fe0-954eeb4dfb6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>w1</value>
      <webElementGuid>efa5a52f-8fe2-455b-a213-da50cb8b89f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>typeahead tt-input</value>
      <webElementGuid>75a550a1-df1b-4417-96a5-9bbc55c14840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asal_sekolah_id-fake</value>
      <webElementGuid>3da4596b-e87a-4214-b529-ada506e7bab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Asal Sekolah</value>
      <webElementGuid>cd279885-c48f-4476-9b1d-4c0a5044d0a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f4975992-2e3a-4bc1-aab5-a95da35a90ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1b09b431-0183-4da2-bb39-0c6ca2e716a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>b65fe7aa-cb26-4818-b540-43d296ee476b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w1&quot;)</value>
      <webElementGuid>f69e20e3-a8e1-4332-8079-d1769cc5a4e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='w1']</value>
      <webElementGuid>50e810f0-2d2a-46c5-a130-7aeafa6fb1d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab_5']/div[5]/span/input</value>
      <webElementGuid>def0cc5f-b231-4971-af7f-ef63b1ba0099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>228fadfa-db0b-420a-ae5e-6d7ac3c4afa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'w1' and @name = 'asal_sekolah_id-fake' and @placeholder = 'Asal Sekolah']</value>
      <webElementGuid>e01b27b0-17cb-4a88-b0ef-59c730a350ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
