<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No. Ijazah SMA_Dimno_ijazah_sma</name>
   <tag></tag>
   <elementGuidId>7d5fc286-2d8b-4b66-b028-6f6550ec74ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dim-no_ijazah_sma</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dim-no_ijazah_sma']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c19789e5-01a1-44d3-9157-e958e09614db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>888febcb-85fa-4208-a699-ee24f67d7867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dim-no_ijazah_sma</value>
      <webElementGuid>46410188-986c-43db-8199-50c82fab6bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2024f133-1eb6-462c-8a15-7861dae8b931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Dim[no_ijazah_sma]</value>
      <webElementGuid>e774782d-bdf9-4529-9511-34b2a6a500ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>DN-07/M-SMA/13/ 05438143</value>
      <webElementGuid>4bf68604-f400-4ac2-beec-9cf3a18b5c87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>523c47e6-4688-44e2-bffa-d5f1cf0fb195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>No.Ijazah SMA</value>
      <webElementGuid>0571749e-358c-402c-b562-d2aa856cc27d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dim-no_ijazah_sma&quot;)</value>
      <webElementGuid>58b39c39-ff64-404f-8112-90395585cc44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dim-no_ijazah_sma']</value>
      <webElementGuid>fbe8a49c-216c-47ba-a28c-70daa3f94ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab_5']/div[3]/div/input</value>
      <webElementGuid>05ebee07-57e6-4bd0-b0c2-2b5dc55428f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div/input</value>
      <webElementGuid>062c3b93-d1a3-472a-a785-7a2fd6746aa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dim-no_ijazah_sma' and @name = 'Dim[no_ijazah_sma]' and @placeholder = 'No.Ijazah SMA']</value>
      <webElementGuid>3877b53f-9684-4683-abf7-990fb8da7ed0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
