<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Ibu_Dimnama_ibu</name>
   <tag></tag>
   <elementGuidId>34e33441-420e-4ddf-80ec-61a1c1903cde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dim-nama_ibu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dim-nama_ibu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ce57164-44a5-4a39-829f-729c53aa9a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>891c77bf-62fb-4900-8aaa-2c9848a20a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dim-nama_ibu</value>
      <webElementGuid>61421bda-4305-4d72-9c5f-a0d6eeb7673c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f752f574-171d-4c1f-ba61-02665db2c43d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Dim[nama_ibu]</value>
      <webElementGuid>f2fc76a6-0700-4cd1-a708-29f5bef72d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Remendi Manalu</value>
      <webElementGuid>1353989d-b8ac-4227-98bf-43f9d4112e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>7f2477dc-e9a9-4e12-9642-9fa9fb00c561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Ibu</value>
      <webElementGuid>581ed629-4b37-4181-a514-19eaf4df3e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4434399f-ae3c-4b81-be0a-713f92ff6296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dim-nama_ibu&quot;)</value>
      <webElementGuid>2b2ac410-0f47-4321-9f27-99196d1d8918</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dim-nama_ibu']</value>
      <webElementGuid>29e2e417-1185-4f8f-90f7-07fa15eddeff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab_4']/div[4]/div/input</value>
      <webElementGuid>4cd2ef91-ccb5-4baf-af5b-554ee46e4902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/div/input</value>
      <webElementGuid>adbf9173-0d5c-48fd-a357-909de016d24a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dim-nama_ibu' and @name = 'Dim[nama_ibu]' and @placeholder = 'Nama Ibu']</value>
      <webElementGuid>d3488cc9-c3d9-4c99-a314-36029a508d5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
