<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Home_fa fa-gear</name>
   <tag></tag>
   <elementGuidId>b24659d6-9f6a-4817-97d2-b5f08a614b73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-gear</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='main-content']/div[2]/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>98f90f6b-664a-4ab5-ab45-053be1eb2f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-gear</value>
      <webElementGuid>2954a718-9ef9-49a1-8046-83a9def2ffd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;pull-right&quot;]/div[@class=&quot;btn-group&quot;]/button[@class=&quot;btn btn-default btn-flat btn-set btn-sm dropdown-toggle&quot;]/span[@class=&quot;fa fa-gear&quot;]</value>
      <webElementGuid>5986a4ff-efca-4eca-bf0b-2b3c36833719</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-content']/div[2]/div/button/span</value>
      <webElementGuid>afbe6716-7be6-43ed-8069-208c3e91f151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>07ac2ab1-20de-46cf-a5cc-14ccfe99d9f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
