<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_LoginFormusername</name>
   <tag></tag>
   <elementGuidId>1e36b885-c972-499d-94ee-b7faeed4d40e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginform-username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loginform-username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc3db642-41b5-4112-9233-888b869808e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1f305bc0-5c4a-4c8c-97b7-d16217076026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginform-username</value>
      <webElementGuid>c1ebcb48-7426-4c0d-accb-135dd5bdb38e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bbd8dd58-52df-4093-aab8-7b43fb67acdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LoginForm[username]</value>
      <webElementGuid>2a7c2235-86ca-4ed1-9739-790a71c008a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>85f32104-7835-42a3-b55c-1b8abd354442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>255113ca-534e-4788-8afd-2990bb134a43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginform-username&quot;)</value>
      <webElementGuid>45a8e41b-e5a4-446d-a442-7a41aa6174c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loginform-username']</value>
      <webElementGuid>ea67582a-cf7c-4419-8ebd-9b4d66f68d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/div/div/input</value>
      <webElementGuid>04f3741d-d617-4696-a87c-164e1b5c3cb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>b84abf85-2810-4987-baf4-34ba4da6aa92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'loginform-username' and @name = 'LoginForm[username]']</value>
      <webElementGuid>4939b69b-c682-4f0d-a506-bf1e8b9e2147</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
